[package]
name = "happiAPI"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
glob = "0.3.2"
reqwest = { version = "0.12.15", features = ["json"] }
rocket = "0.5.1"
serde = "1.0.219"
toml = "0.8.22"
